# My contact information.
title: Simon Benjamin Orion Parent
email: sboparen@gmail.com

# Hosting settings.
url: "https://sboparen.github.io"

# Markdown settings.
markdown: kramdown
kramdown:
    entity_output: true
    smart_quotes: ["apos", "apos", "quot", "quot"]

# Exclusions for resume/
exclude: [
    '/resume/*.html',
    '/resume/*.log',
    '/resume/*.sh',
    '/resume/resume.*',
]

plugins:
  - jekyll-redirect-from
